
-   CIE - 1 20 Quiz Exam -- Project
-   CIE - 2 20 Quiz 1-4   (400 convert in 20)
-   CIE - 3 10

-   SEE - Nptel Exam 100 (Converted Inh 100 To 75)
-                     (75 That Converted In 50)

---

#**Data Science**
-   Python
-   ML  (Machine Lerning)
-   AI  (Artificial Inteligent)
-   DL  (Deep Lernning)

#Data Can Be In Form Of
-   Stractured Data
-   Un Stractured Data

#For Data Scientist In Trend
-   Python
    
  


##What is Data Science Job?
A data science job involves using various techniques, algorithms, and tools to extract insights and knowledge from structured and unstructured data. Here are some of the key data science job roles:

#**Data Scientist:**
Responsibilities: Analyzing large datasets, developing machine learning models, interpreting results, and providing insights to inform business decisions.

**Skills:** Proficiency in programming languages like Python or R, expertise in statistics and machine learning algorithms, data visualization skills, and domain knowledge in the relevant industry.
#**Data Analyst:**
**Responsibilities:**Collecting, cleaning, and analyzing data to identify trends, patterns, and insights. Often involves creating reports and dashboards to communicate findings to stakeholders.

**Skills:** Strong proficiency in SQL for data querying, experience with data visualization tools like Tableau or Power BI, basic statistical knowledge, and familiarity with Excel or Google Sheets.
#**Machine Learning Engineer:**
**Responsibilities:** Building and deploying machine learning models at scale, optimizing model performance, and integrating them into production systems.

**Skills:** Proficiency in programming languages like Python or Java, experience with machine learning frameworks like TensorFlow or PyTorch, knowledge of cloud platforms like AWS or Azure, and software engineering skills for developing scalable solutions.
#**Data Engineer:**
**Responsibilities:** Designing and building data pipelines to collect, transform, and store large volumes of data. Ensuring data quality, reliability, and scalability.

**Skills:** Expertise in database systems like SQL and NoSQL, proficiency in programming languages like Python or Java, experience with big data technologies like Hadoop or Spark, and knowledge of data warehousing concepts.
#**Business Intelligence (BI) Analyst:**
**Responsibilities:** Gathering requirements from business stakeholders, designing and developing BI reports and dashboards, and providing data-driven insights to support strategic decision-making.

**Skills:** Proficiency in BI tools like Tableau, Power BI, or Looker, strong SQL skills for data querying, understanding of data visualization principles, and ability to translate business needs into technical solutions.
#**Data Architect:**
**Responsibilities:** Designing the overall structure of data systems, including databases, data lakes, and data warehouses. Defining data models, schemas, and data governance policies.

**Skills:** Deep understanding of database technologies and architectures, experience with data modeling tools like ERWin or Visio, knowledge of data integration techniques, and familiarity with data security and compliance regulations.

- Leadingindia.ai
- kaggle.com

#NumPy




In [ ]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)
print(type(a))
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [ ]:
b=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(b)
print(type(b))
print(b.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
<class 'numpy.ndarray'>
(5, 2)


In [ ]:
c=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
print(c)
print(type(c))
print(c.shape)

[[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]
<class 'numpy.ndarray'>
(4, 3)


In [ ]:
d=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])
print(d)
print(type(d))
print(d.shape)

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(3, 4)


In [ ]:
e=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(e)
print(type(e))
print(e.shape)

[[1 2 3 4 5]
 [3 4 5 6 7]]
<class 'numpy.ndarray'>
(2, 5)


---

# **27/06/2024**

#Research paper

In [ ]:
# https://icaitpr.org/

#Google Scohlar

In [ ]:
# https://scholar.google.com/

#IEEE Xpolar

In [ ]:
# https://ieeexplore.ieee.org/Xplore/home.jsp

#Leading India AI

In [ ]:
#https://www.leadingindia.ai/

#Research

In [ ]:
#https://www.researchgate.net/

#**28-06-2024**

In [ ]:
import numpy as np
c=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]);
print(c)
print((type(c)))
print(c.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>
(2, 3, 4)


In [ ]:
a=np.array([0,1,2,3,4,5,6,7,8,9,True])
print(a)
print((type(a)))
print(a.shape)

[0 1 2 3 4 5 6 7 8 9 1]
<class 'numpy.ndarray'>
(11,)


In [ ]:
d=np.array([0,1,2,3,4,5,6,7,8,9],"complex")
print(d)

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]


In [ ]:
e=np.array([0,1,2,3,4,5,6,7,8,9],"int")
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
f=np.array([0,1,2,3,4,5,6,7,8,9],"float")
print(f)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
g=np.array([0,1,2,3,4,5,6,7,8,9],"bool")
print(g)

[False  True  True  True  True  True  True  True  True  True]


In [ ]:
x=np.array([2,3,'4',3,4])
print(x)

['2' '3' '4' '3' '4']


#**Built-In Functions**

    numpy.linspace()

    

In [ ]:
y=np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=False)
print(y)
print(type(y))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
<class 'numpy.ndarray'>


In [ ]:
z=np.linspace(start=1,stop=1000,num=25,endpoint=True,retstep=True)
print(z)
print('------------------------------------------------')
print(type(z))

(array([   1.   ,   42.625,   84.25 ,  125.875,  167.5  ,  209.125,
        250.75 ,  292.375,  334.   ,  375.625,  417.25 ,  458.875,
        500.5  ,  542.125,  583.75 ,  625.375,  667.   ,  708.625,
        750.25 ,  791.875,  833.5  ,  875.125,  916.75 ,  958.375,
       1000.   ]), 41.625)
------------------------------------------------
<class 'tuple'>


In [ ]:
w=np.linspace(start=1,stop=100,num=25,endpoint=True,retstep=True)
print(w)
print('------------------------------------------------')
print(type(w))

(array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ]), 4.125)
------------------------------------------------
<class 'tuple'>


In [ ]:
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [ ]:
v=np.arange(1,10)
print(v)

[1 2 3 4 5 6 7 8 9]


In [ ]:
u=np.arange(10,0,-1)
print(u)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(1,datatype="float")

In [ ]:
np.random.rand(5)

array([0.01061423, 0.84403457, 0.08890008, 0.64798908, 0.63730901])

In [ ]:
np.random.rand(5)

array([0.82562932, 0.4815238 , 0.73810749, 0.4423878 , 0.39526501])

In [ ]:
np.random.rand(5,2)

array([[0.51846075, 0.85903517],
       [0.53080633, 0.77051831],
       [0.08017799, 0.93703458],
       [0.18681983, 0.73534957],
       [0.62606336, 0.34998735]])

In [ ]:
np.random.rand(5,2)

array([[0.0334926 , 0.94425957],
       [0.88321963, 0.24820722],
       [0.580172  , 0.75017828],
       [0.03803449, 0.78461282],
       [0.89852766, 0.01733242]])

In [ ]:
np.random.rand(6)

array([0.20010164, 0.36842716, 0.88664771, 0.53486257, 0.22498208,
       0.25284579])

In [ ]:
np.random.randint(1,7)

1

In [ ]:
#take a two person  roling dies whenever 6 stop game and ans in the that trial that get win
#like suresh=[3,5,6]
#In the 3 trial he got 6
#like ramesh=[1,2,4,3,5,6]
#In the 6 trial he got 6
#suresh won a game

import random

def roll_die():
    return random.randint(1, 6)

def play_game(player_name):
    rolls = 0
    while True:
        rolls += 1
        result = roll_die()
        print(f"{player_name} rolled: {result}")
        if result == 6:
            break
    return rolls

# Example players
suresh = play_game("Suresh")
ramesh = play_game("Ramesh")

# Determine the winner
if suresh < ramesh:
    print("Suresh won!")
elif ramesh < suresh:
    print("Ramesh won!")
else:
    print("It's a tie!")


Suresh rolled: 2
Suresh rolled: 1
Suresh rolled: 4
Suresh rolled: 3
Suresh rolled: 6
Ramesh rolled: 2
Ramesh rolled: 5
Ramesh rolled: 3
Ramesh rolled: 3
Ramesh rolled: 2
Ramesh rolled: 4
Ramesh rolled: 6
Suresh won!


In [ ]:
import random

def roll_die():
    return random.randint(1, 6)

def play_game():
    suresh = []
    ramesh = []

    while True:
        result = roll_die()
        suresh.append(result)
        if result == 6:
            break

    while True:
        result = roll_die()
        ramesh.append(result)
        if result == 6:
            break

    if len(suresh) < len(ramesh):
        return ["Suresh", suresh]
    else:
        return ["Ramesh", ramesh]

# Example usage:
winner, game_result = play_game()
print(f"{winner} won the game in trial {len(game_result)}. Results: {game_result}")


Ramesh won the game in trial 3. Results: [3, 3, 6]


In [ ]:
import random

def roll_die():
    return random.randint(1, 6)

def play_game(player_name):
    trials = 0
    while True:
        trials += 1
        result = roll_die()
        print(f"{player_name}: Rolled {result}")
        if result == 6:
            print(f"{player_name} won the game in {trials} trials!\n")
            return trials

# Main program
if __name__ == "__main__":
    suresh_trials = play_game("Suresh")
    ramesh_trials = play_game("Ramesh")

    if suresh_trials < ramesh_trials:
        print("Suresh won the game!")
    elif ramesh_trials < suresh_trials:
        print("Ramesh won the game!")
    else:
        print("It's a tie!")


Suresh: Rolled 5
Suresh: Rolled 2
Suresh: Rolled 1
Suresh: Rolled 4
Suresh: Rolled 2
Suresh: Rolled 5
Suresh: Rolled 4
Suresh: Rolled 2
Suresh: Rolled 5
Suresh: Rolled 1
Suresh: Rolled 1
Suresh: Rolled 5
Suresh: Rolled 4
Suresh: Rolled 5
Suresh: Rolled 1
Suresh: Rolled 2
Suresh: Rolled 1
Suresh: Rolled 1
Suresh: Rolled 3
Suresh: Rolled 6
Suresh won the game in 20 trials!

Ramesh: Rolled 1
Ramesh: Rolled 6
Ramesh won the game in 2 trials!

Ramesh won the game!


In [ ]:
import numpy as np

def roll_die():
    return np.random.randint(1, 7)  # randint is inclusive of low and exclusive of high

def play_game(player_name):
    trials = 0
    while True:
        trials += 1
        result = roll_die()
        print(f"{player_name}: Rolled {result}")
        if result == 6:
            print(f"In the {trials} trial, {player_name} got 6")
            return trials

# Main program
if __name__ == "__main__":
    np.random.seed()  # For reproducibility of random numbers
    suresh_trials = play_game("Suresh")
    ramesh_trials = play_game("Ramesh")

    if suresh_trials < ramesh_trials:
        print("Suresh won a game!")
    elif ramesh_trials < suresh_trials:
        print("Ramesh won a game!")
    else:
        print("It's a tie!")


Suresh: Rolled 5
Suresh: Rolled 2
Suresh: Rolled 3
Suresh: Rolled 1
Suresh: Rolled 5
Suresh: Rolled 5
Suresh: Rolled 3
Suresh: Rolled 1
Suresh: Rolled 3
Suresh: Rolled 2
Suresh: Rolled 1
Suresh: Rolled 2
Suresh: Rolled 4
Suresh: Rolled 3
Suresh: Rolled 4
Suresh: Rolled 4
Suresh: Rolled 1
Suresh: Rolled 4
Suresh: Rolled 5
Suresh: Rolled 2
Suresh: Rolled 5
Suresh: Rolled 4
Suresh: Rolled 4
Suresh: Rolled 3
Suresh: Rolled 6
In the 25 trial, Suresh got 6
Ramesh: Rolled 5
Ramesh: Rolled 5
Ramesh: Rolled 2
Ramesh: Rolled 1
Ramesh: Rolled 5
Ramesh: Rolled 5
Ramesh: Rolled 5
Ramesh: Rolled 3
Ramesh: Rolled 3
Ramesh: Rolled 5
Ramesh: Rolled 1
Ramesh: Rolled 5
Ramesh: Rolled 4
Ramesh: Rolled 4
Ramesh: Rolled 6
In the 15 trial, Ramesh got 6
Ramesh won a game!


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
a[0:3]
print(a)
print(a[4])
print(a[-5])
print(a[-7])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
5
5
3


In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

result = []
index = 0
step = 2

for i in range(len(a)):
    if index < len(a):
        result.append(a[index])
        index += step
        step += 1
    else:
        break

print(result)

[1, 3, 6, 10, 15]


In [ ]:
moves = "YourStringHere"  # Replace "YourStringHere" with your actual moves string
ans = 0
for i in moves:
    if i == 'R':
        ans += 1
    else:
        ans -= 1

h = 0
for i in moves:
    if i == 'L':
        h -= 1
    else:
        h += 1

result = max(abs(h), abs(ans))
print(result)


14


In [ ]:
import numpy as np
g=np.arange(start=1,stop=10).reshape(3,3)
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(' ')
b=np.arange(start=11,stop=20).reshape(3,3)
print(b)
print(' ')
print("===>Addition \n",np.add(a,b))
print(' ')
print("===>Substraction \n",np.subtract(a,b))
print(' ')
print("===>Multiplication \n",np.multiply(a,b))
print(' ')
print("===>Division \n",np.divide(a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[11 12 13]
 [14 15 16]
 [17 18 19]]
 
===>Addition 
 [[12 14 16]
 [18 20 22]
 [24 26 28]]
 
===>Substraction 
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
 
===>Multiplication 
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
 
===>Division 
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


---
#IN Microsot


In [ ]:
import numpy as np

b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20

In [ ]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()

In [ ]:
import numpy as np
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


In [ ]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned)

Tom      8
Kris     2
Ahmad    5
Beau     6
dtype: int64


In [ ]:
import pandas as pd

certificates_earned = pd.Series(
    [8, 2, 5, 6],
    index=['Tom', 'Kris', 'Ahmad', 'Beau']
)

print(certificates_earned[certificates_earned > 5])

Tom     8
Beau    6
dtype: int64


In [ ]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})

certificates_earned.index = ['Tom', 'Kris', 'Ahmad', 'Beau']

print(certificates_earned.iloc[2])

Certificates        5
Time (in months)    9
Name: Ahmad, dtype: int64


In [ ]:
import pandas as pd

certificates_earned = pd.DataFrame({
    'Certificates': [8, 2, 5, 6],
    'Time (in months)': [16, 5, 9, 12]
})
names = ['Tom', 'Kris', 'Ahmad', 'Beau']

certificates_earned.index = names
longest_streak = pd.Series([13, 11, 9, 7], index=names)
certificates_earned['Longest streak'] = longest_streak

print(certificates_earned)

       Certificates  Time (in months)  Longest streak
Tom               8                16              13
Kris              2                 5              11
Ahmad             5                 9               9
Beau              6                12               7


In [ ]:
import pandas as pd
import numpy as np

s = pd.Series(['a', 3, np.nan, 1, np.nan])

print(s.notnull().sum())

3


In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([np.nan, 1, 2, np.nan, 3])
s = s.fillna(method='ffill')

print(s)

0    NaN
1    1.0
2    2.0
3    2.0
4    3.0
dtype: float64


In [ ]:
import csv

with open(__A__, 'r') as fp:
    reader = csv.reader(fp, delimiter=__B__)
    next(reader)
    for index, values in enumerate(reader):
        name, certs_num, months_num = values
        print(f"{name} earned {__C__} certificates in {months_num} months")

NameError: name '__A__' is not defined

---

#11-07-2024


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pwd

'/content'

In [ ]:
# 10
a=5
b=3
print(a&b)

1


In [ ]:
x=10
y=5
z=3
ans=x+y%z
print(ans)

12


In [ ]:
x=15
y=str(float(x))
print(type(y))

<class 'str'>


In [ ]:
a=-21//7
print(a)

-3


In [ ]:
a=3
b="12"
print(a*b)

121212


In [ ]:
# j / g  # 6 / 3.3 = 1.8181818181818181 (float)
# j // g  # 6 // 3.3 = 1.0 (float)
print(6/3.3)
print(6//3.3)

1.8181818181818183
1.0


In [ ]:
x='Mayur'
#print(str(float(x)))   #ValueError
#print(x.float())       #AttributeError
#print(float(x))         #ValueError

ValueError: could not convert string to float: 'Mayur'

In [ ]:
1 variable = 1
variable 1 = 2
variable1 = 3
variable# = 4
print(variable 1)
print(varible1)
print(1 variable)
print(variable#)

SyntaxError: invalid syntax (<ipython-input-2-3ee87bc1586e>, line 1)